export const CONFLICT_START = '2026-02-28'; // automated test — will revert

export const FACTORS = [
  {
    id: 'flights',
    name: 'DXB Flight Operations',
    shortName: 'Flights',
    weight: 4,
    icon: 'departure_board',
    inverse: false,
    description: 'Total scheduled departures from DXB per day',
    rubric: [
      { score: 1, label: '0-100', desc: 'Airport closed / emergency-only' },
      { score: 2, label: '100-350', desc: '~10-30% capacity' },
      { score: 3, label: '350-700', desc: '~30-60% capacity' },
      { score: 4, label: '700-1000', desc: '~60-85% capacity' },
      { score: 5, label: '1000+', desc: '~85%+ of normal' },
    ],
    sources: [
      { name: 'FlightRadar24 DXB', url: 'https://www.flightradar24.com/data/airports/dxb/statistics' },
      { name: 'Dubai Airports', url: 'https://dubaiairports.ae/flight-status?type=departures' },
    ],
  },
  {
    id: 'incidents',
    name: 'UAE Missile/Drone Incidents',
    shortName: 'Incidents',
    weight: 5,
    icon: 'warning',
    inverse: true,
    description: 'Confirmed strikes, intercepts, debris incidents in UAE (inverse)',
    rubric: [
      { score: 1, label: '5+', desc: 'Multiple strikes, civilian casualties' },
      { score: 2, label: '3-4', desc: 'Intercepts with debris damage' },
      { score: 3, label: '1-2', desc: 'All intercepted, no civilian impact' },
      { score: 4, label: '0', desc: 'Clean for 24-48hrs' },
      { score: 5, label: '0', desc: 'Clean for 72+ consecutive hours' },
    ],
    sources: [
      { name: 'GCC Missile Tracker', url: 'https://takahser.github.io/uae-dashboard/' },
      { name: 'Wikipedia Timeline', url: 'https://en.wikipedia.org/wiki/Timeline_of_the_2026_Iran_conflict' },
      { name: 'Conflict Tracker', url: 'https://war-tracker-me.netlify.app/' },
    ],
  },
  {
    id: 'hormuz',
    name: 'Strait of Hormuz Transits',
    shortName: 'Hormuz',
    weight: 2,
    icon: 'sailing',
    inverse: false,
    description: 'Commercial vessel crossings per day',
    rubric: [
      { score: 1, label: '0-2', desc: 'Effective blockade' },
      { score: 2, label: '3-10', desc: 'Iranian-flagged / dark transits only' },
      { score: 3, label: '10-25', desc: 'Selective reopening' },
      { score: 4, label: '25-45', desc: 'Western carriers resuming' },
      { score: 5, label: '45+', desc: 'Near-normal traffic' },
    ],
    sources: [
      { name: 'Windward Blog', url: 'https://windward.ai/blog/' },
      { name: 'HormuzTracker', url: 'https://www.hormuztracker.com/' },
    ],
  },
  {
    id: 'oil',
    name: 'Brent Crude Oil Price',
    shortName: 'Brent',
    weight: 1,
    icon: 'oil_barrel',
    inverse: false,
    description: 'Daily Brent crude spot price (USD/barrel)',
    rubric: [
      { score: 1, label: '$120+', desc: 'Extreme crisis premium' },
      { score: 2, label: '$100-120', desc: 'Severe disruption priced in' },
      { score: 3, label: '$85-100', desc: 'Elevated conflict premium' },
      { score: 4, label: '$70-85', desc: 'Normalising toward pre-conflict' },
      { score: 5, label: '<$70', desc: 'Pre-conflict range or below' },
    ],
    sources: [
      { name: 'TradingView', url: 'https://www.tradingview.com/symbols/TVC-UKOIL/' },
      { name: 'Yahoo Finance', url: 'https://finance.yahoo.com/quote/BZ%3DF/' },
    ],
  },
  {
    id: 'advisory',
    name: 'Travel Advisory Level',
    shortName: 'Advisory',
    weight: 3,
    icon: 'policy',
    inverse: false,
    description: 'Worst of US/UK/AU government advisories',
    rubric: [
      { score: 1, label: 'DNT + Evac', desc: '"Do Not Travel" + embassy evacuation' },
      { score: 2, label: 'DNT / Closed', desc: '"Do Not Travel" or embassy fully closed' },
      { score: 3, label: 'Reconsider', desc: '"Reconsider Travel" + limited embassy' },
      { score: 4, label: 'High Caution', desc: '"Exercise High Caution" + embassy reopening' },
      { score: 5, label: 'Normal', desc: 'Normal precautions' },
    ],
    sources: [
      { name: 'US State Dept', url: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/united-arab-emirates-travel-advisory.html' },
      { name: 'UK FCDO', url: 'https://www.gov.uk/foreign-travel-advice/united-arab-emirates' },
      { name: 'AU Smartraveller', url: 'https://www.smartraveller.gov.au/destinations/middle-east/united-arab-emirates' },
    ],
  },
  {
    id: 'ceasefire',
    name: 'Ceasefire & Diplomatic Status',
    shortName: 'Ceasefire',
    weight: 5,
    icon: 'handshake',
    inverse: false,
    description: 'Qualitative state of ceasefire negotiations',
    rubric: [
      { score: 1, label: 'Escalation', desc: 'New fronts, widening conflict' },
      { score: 2, label: 'Sustained', desc: 'Strikes continuing, no talks' },
      { score: 3, label: 'Deceleration', desc: 'Strike rate declining, backchannel contacts' },
      { score: 4, label: 'Active Talks', desc: 'Named mediators, both sides at table' },
      { score: 5, label: 'Ceasefire', desc: 'Formal ceasefire holding 48+ hours' },
    ],
    sources: [
      { name: 'Al Jazeera', url: 'https://www.aljazeera.com/news/' },
      { name: 'Reuters', url: 'https://www.reuters.com/world/' },
    ],
  },
  {
    id: 'airport_threat',
    name: 'DXB Airport Direct Threat',
    shortName: 'DXB Threat',
    weight: 4,
    icon: 'flight',
    inverse: false,
    description: 'Days since last direct threat to DXB',
    rubric: [
      { score: 1, label: 'Today', desc: 'Airport hit, closed, or airspace closure' },
      { score: 2, label: '1-2 days', desc: 'Incident within 48 hours' },
      { score: 3, label: '3-5 days', desc: 'Last incident 3-5 days ago' },
      { score: 4, label: '6-10 days', desc: 'Last incident 6-10 days ago' },
      { score: 5, label: '10+ days', desc: 'No DXB incident in 10+ days' },
    ],
    sources: [
      { name: 'TravelPirates', url: 'https://www.travelpirates.com/captains-log/' },
      { name: '@DXB Twitter', url: 'https://twitter.com/DXB' },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare Access',
    shortName: 'Healthcare',
    weight: 5,
    icon: 'local_hospital',
    inverse: false,
    description: 'OB/GYN, delivery hospital, prenatal care availability',
    rubric: [
      { score: 1, label: 'Closed', desc: 'Hospitals overwhelmed or closed' },
      { score: 2, label: 'Emergency Only', desc: 'Routine appointments cancelled' },
      { score: 3, label: 'Intermittent', desc: 'Open with disruptions, staff shortages' },
      { score: 4, label: 'Mostly Normal', desc: 'OB/GYN available, insurance working' },
      { score: 5, label: 'Full Normal', desc: 'Complete prenatal care, no disruptions' },
    ],
    sources: [
      { name: 'DHA', url: 'https://www.dha.gov.ae/' },
      { name: 'Direct clinic call', url: '' },
    ],
  },
  {
    id: 'exit',
    name: 'Exit Viability',
    shortName: 'Exit',
    weight: 4,
    icon: 'flight_takeoff',
    inverse: false,
    description: 'Ability to leave Dubai within 24hrs with family',
    rubric: [
      { score: 1, label: 'None', desc: 'No flights within 48hrs, borders closed' },
      { score: 2, label: 'Limited', desc: '>3x price, frequent cancellations' },
      { score: 3, label: 'Expensive', desc: 'Next-day at 2-3x, cancellation risk' },
      { score: 4, label: 'Available', desc: 'Same/next-day at 1.5-2x, multiple routes' },
      { score: 5, label: 'Normal', desc: 'Normal pricing, multiple daily options' },
    ],
    sources: [
      { name: 'Skyscanner', url: 'https://www.skyscanner.com/' },
      { name: 'FlightRadar24', url: 'https://www.flightradar24.com/data/airports/dxb/statistics' },
    ],
  },
];

export const TOTAL_WEIGHT = FACTORS.reduce((sum, f) => sum + f.weight, 0); // 33

export const VERDICTS = [
  { min: 80, max: 100, label: 'GO', color: '#00FF66', bg: 'rgba(0,255,102,0.12)', meaning: 'Conditions support return. Proceed with confirmed bookings and contingency plan.' },
  { min: 65, max: 79, label: 'CONDITIONAL GO', color: '#B8FF00', bg: 'rgba(184,255,0,0.12)', meaning: 'Acceptable if strong pull factors and tested exit plan. Monitor daily.' },
  { min: 45, max: 64, label: 'HOLD', color: '#FFD600', bg: 'rgba(255,214,0,0.12)', meaning: 'Stay in Kazakhstan. Conditions improving but not stable enough.' },
  { min: 25, max: 44, label: 'NO GO', color: '#FF6B00', bg: 'rgba(255,107,0,0.12)', meaning: 'Do not return. Active risk to family safety.' },
  { min: 0, max: 24, label: 'RED', color: '#FF003C', bg: 'rgba(255,0,60,0.12)', meaning: 'Dangerous. Extend stay. Do not attempt travel.' },
];

export const BASELINE_DATA = [
  { date: '2026-02-27', scores: { flights: 5, incidents: 5, hormuz: 5, oil: 4, advisory: 5, ceasefire: 4, airport_threat: 5, healthcare: 5, exit: 5 }, note: 'Normal operations. Negotiations in Geneva ongoing. US military buildup underway but no strikes.' },
  { date: '2026-02-28', scores: { flights: 1, incidents: 2, hormuz: 2, oil: 2, advisory: 2, ceasefire: 1, airport_threat: 1, healthcare: 3, exit: 1 }, note: 'US-Israel strikes begin 02:30 EST. Khamenei killed. UAE airspace closed. DXB shut.' },
  { date: '2026-03-01', scores: { flights: 1, incidents: 1, hormuz: 1, oil: 2, advisory: 1, ceasefire: 1, airport_threat: 1, healthcare: 2, exit: 1 }, note: 'Iranian counter-strikes hit UAE, Bahrain, Kuwait. Shelter-in-place orders. All airports closed.' },
  { date: '2026-03-02', scores: { flights: 1, incidents: 1, hormuz: 1, oil: 1, advisory: 1, ceasefire: 1, airport_threat: 1, healthcare: 2, exit: 1 }, note: 'Strikes on Dubai, Abu Dhabi, Doha. AWS data centers hit. Hezbollah joins conflict. IRGC confirms Hormuz closed.' },
  { date: '2026-03-03', scores: { flights: 1, incidents: 1, hormuz: 1, oil: 1, advisory: 1, ceasefire: 1, airport_threat: 1, healthcare: 2, exit: 1 }, note: 'US Embassy orders departure. Level 3 advisory. Iran publicly rejects ceasefire.' },
  { date: '2026-03-04', scores: { flights: 1, incidents: 2, hormuz: 1, oil: 1, advisory: 2, ceasefire: 2, airport_threat: 1, healthcare: 2, exit: 1 }, note: 'State Dept evac flights begin from Abu Dhabi/Dubai. Iran backchannel to CIA reported via CNN.' },
  { date: '2026-03-05', scores: { flights: 2, incidents: 2, hormuz: 1, oil: 2, advisory: 2, ceasefire: 2, airport_threat: 2, healthcare: 3, exit: 2 }, note: 'flydubai resumes limited ops. Araghchi rejects talks on NBC. Iranian missile rate declining.' },
  { date: '2026-03-06', scores: { flights: 3, incidents: 2, hormuz: 1, oil: 2, advisory: 2, ceasefire: 2, airport_threat: 2, healthcare: 3, exit: 2 }, note: 'Emirates restores 83 destinations. DXB partial reopening. P&I insurance withdrawn for Hormuz.' },
  { date: '2026-03-07', scores: { flights: 2, incidents: 2, hormuz: 1, oil: 2, advisory: 2, ceasefire: 2, airport_threat: 1, healthcare: 3, exit: 2 }, note: 'REGRESSION. Drone explodes next to DXB Concourse A. Flights halted then resumed.' },
  { date: '2026-03-08', scores: { flights: 3, incidents: 2, hormuz: 1, oil: 2, advisory: 2, ceasefire: 2, airport_threat: 2, healthcare: 3, exit: 3 }, note: 'Hormuz at record low — 2 transits all day. Israel hit 400+ Iranian targets over weekend.' },
  { date: '2026-03-09', scores: { flights: 3, incidents: 3, hormuz: 1, oil: 2, advisory: 2, ceasefire: 2, airport_threat: 3, healthcare: 3, exit: 3 }, note: 'First exit from RED. China/Russia/France contact Iran re ceasefire. Emirates at 84 destinations.' },
  { date: '2026-03-10', scores: { flights: 3, incidents: 3, hormuz: 1, oil: 2, advisory: 2, ceasefire: 2, airport_threat: 3, healthcare: 3, exit: 3 }, note: 'Trump says war over "pretty quickly" but "not this week." Araghchi says fight "as long as it takes."' },
  { date: '2026-03-11', scores: { flights: 3, incidents: 3, hormuz: 1, oil: 2, advisory: 2, ceasefire: 2, airport_threat: 3, healthcare: 3, exit: 3 }, note: 'Day 11. Embassy still closed. DXB ~60% ops. No ceasefire. Family departs for Almaty tonight.' },
  { date: '2026-03-12', scores: { flights: 3, incidents: 2, hormuz: 1, oil: 3, advisory: 2, ceasefire: 2, airport_threat: 2, healthcare: 3, exit: 3 }, note: 'Day 12. DXB drones injured 4 near terminal yesterday. IRGC vows total Hormuz blockade. Brent eases to $89. Mojtaba Khamenei installed as new supreme leader.' },
];

export const ALL_SOURCE_URLS = [
  { name: 'FlightRadar24 DXB', url: 'https://www.flightradar24.com/data/airports/dxb/statistics' },
  { name: 'GCC Missile Tracker', url: 'https://takahser.github.io/uae-dashboard/' },
  { name: 'Windward Hormuz', url: 'https://windward.ai/blog/' },
  { name: 'Brent Crude', url: 'https://www.tradingview.com/symbols/TVC-UKOIL/' },
  { name: 'US Advisory', url: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/united-arab-emirates-travel-advisory.html' },
  { name: 'UK Advisory', url: 'https://www.gov.uk/foreign-travel-advice/united-arab-emirates' },
  { name: 'AU Advisory', url: 'https://www.smartraveller.gov.au/destinations/middle-east/united-arab-emirates' },
  { name: 'Al Jazeera', url: 'https://www.aljazeera.com/news/' },
  { name: 'TravelPirates DXB', url: 'https://www.travelpirates.com/captains-log/' },
  { name: 'Skyscanner', url: 'https://www.skyscanner.com/' },
];
